"""baseline schema

Revision ID: cca35f727fa3
Revises: 
Create Date: 2026-07-13 11:43:23.494736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca35f727fa3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_global_config',
    sa.Column('agent_key', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('agent_key')
    )
    op.create_table('rooms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=256), nullable=False),
    sa.Column('enrichment_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cycles_used', sa.Integer(), nullable=False),
    sa.Column('cycle_limit', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'paused_awaiting_human')", name='ck_rooms_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_name')
    )
    op.create_table('agent_skills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=True),
    sa.Column('agent_key', sa.String(length=32), nullable=False),
    sa.Column('skill_name', sa.String(length=256), nullable=False),
    sa.Column('skill_type', sa.String(length=8), nullable=False),
    sa.Column('blob_path', sa.String(length=1024), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_skills_agent_key'), 'agent_skills', ['agent_key'], unique=False)
    op.create_index(op.f('ix_agent_skills_room_id'), 'agent_skills', ['room_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=True),
    sa.Column('actor', sa.String(length=256), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_room_id'), 'audit_log', ['room_id'], unique=False)
    op.create_table('gdrive_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('google_folder_id', sa.String(length=256), nullable=True),
    sa.Column('google_folder_name', sa.String(length=512), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'connected', 'linked', 'error', 'revoked')", name='ck_gdrive_connections_status'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('sender_type', sa.String(length=16), nullable=False),
    sa.Column('sender_name', sa.String(length=256), nullable=False),
    sa.Column('agent_key', sa.String(length=32), nullable=True),
    sa.Column('mention_target', sa.String(length=32), nullable=True),
    sa.Column('cycle_number', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("sender_type IN ('human', 'agent', 'system')", name='ck_messages_sender_type'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_room_seq', 'messages', ['room_id', 'seq'], unique=False)
    op.create_table('room_agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('agent_key', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'agent_key')
    )
    op.create_table('room_invites',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_room_invites_room_id'), 'room_invites', ['room_id'], unique=False)
    op.create_table('room_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('room_id', sa.String(length=36), nullable=False),
    sa.Column('user_email', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'member')", name='ck_room_members_role'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'user_email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_members')
    op.drop_index(op.f('ix_room_invites_room_id'), table_name='room_invites')
    op.drop_table('room_invites')
    op.drop_table('room_agents')
    op.drop_index('ix_messages_room_seq', table_name='messages')
    op.drop_table('messages')
    op.drop_table('gdrive_connections')
    op.drop_index(op.f('ix_audit_log_room_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_agent_skills_room_id'), table_name='agent_skills')
    op.drop_index(op.f('ix_agent_skills_agent_key'), table_name='agent_skills')
    op.drop_table('agent_skills')
    op.drop_table('rooms')
    op.drop_table('agent_global_config')
    # ### end Alembic commands ###
